# Generated by Django 5.2.9 on 2025-12-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopsettings_bill_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid, including taxes and fees.', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('gateway', models.CharField(default='stripe', max_length=50)),
                ('gateway_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID or equivalent.', max_length=250, null=True, unique=True)),
                ('checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID (cs_...)', max_length=250, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.bill', verbose_name='Associated Bill')),
                ('user_paid', models.ForeignKey(blank=True, help_text='The admin user who initiated the payment/recorded it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
