# Generated by Django 5.2.9 on 2025-12-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bill_due_date_bill_outstanding_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='outstanding_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_last_four',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.bill', verbose_name='Associated Bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('stripe', 'Stripe')], default='cash', max_length=50),
        ),
    ]
